// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'chat.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

String coreVersion() => RustLib.instance.api.crateApiChatCoreVersion();

/// Starts the core, or returns the running one (see `chat_core::CoreSlot::start`).
Future<CoreInfo> coreStart({required String dataDir}) =>
    RustLib.instance.api.crateApiChatCoreStart(dataDir: dataDir);

/// The single event stream of the UI (design 12.2 rule 1).
Stream<ChatEvent> events() => RustLib.instance.api.crateApiChatEvents();

@freezed
sealed class ChatEvent with _$ChatEvent {
  const ChatEvent._();

  const factory ChatEvent.connectionState({
    required int directPeers,
    required bool mailboxOk,
    bool? queueOk,
  }) = ChatEvent_ConnectionState;
  const factory ChatEvent.error({
    required ErrorCode code,
    required String detail,
  }) = ChatEvent_Error;
}

class CoreError implements FrbException {
  final ErrorCode code;
  final String detail;

  const CoreError({required this.code, required this.detail});

  @override
  int get hashCode => code.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          detail == other.detail;
}

class CoreInfo {
  final String version;
  final String instanceId;

  const CoreInfo({required this.version, required this.instanceId});

  @override
  int get hashCode => version.hashCode ^ instanceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          instanceId == other.instanceId;
}

enum ErrorCode { invalidConfig, alreadyStartedDifferentConfig }
